//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Detalles = new HashSet<Detalles>();
        }
    
        public int id_factura { get; set; }
        public int NumeroFac { get; set; }
        public int id_usuarioFac { get; set; }
        public int id_tipoFac { get; set; }
        public string formaPago { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_clienteFac { get; set; }
        public decimal total { get; set; }
        public bool estado_vigencia { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles> Detalles { get; set; }
        public virtual TipoFacturas TipoFacturas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
