//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maderas
    {
        public int idMaderas { get; set; }
        public int id_tipoMad { get; set; }
        public string descipcion { get; set; }
        public bool estadoVigencia { get; set; }
        public int stockActual { get; set; }
        public int stockMinimo { get; set; }
        public decimal precioCosto { get; set; }
        public decimal precioVenta { get; set; }
    
        public virtual TipoMadera TipoMadera { get; set; }
    }
}
