//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Id_usuario { get; set; }
        public int Id_rol_usuario { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string nombre_usuario { get; set; }
        public string pass { get; set; }
        public Nullable<bool> estado_vigencia { get; set; }
        public string sexo { get; set; }
        public string estado_civil { get; set; }
        public string telefono { get; set; }
        public string domicilio { get; set; }
        public string correo { get; set; }
        public string dni { get; set; }
        public System.DateTime fecha_Nacimiento { get; set; }
    
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
